### ISSUE TITLE
[BUG] failed at starting macadam with vfkit a second time

### ISSUE THREAD

**Issue by lstocchi** [cfergeau/crc#13]
### General information

  * OS: macOS 
  * Hypervisor: vfkit
  * Did you run `crc setup` before starting it (Yes/No)? yes
  * Running CRC on: VM

### Steps to reproduce

  1. followed steps from https://github.com/cfergeau/crc/blob/macadam/docs/macadam-testing.md by downloading the micro shift vfkit bundle
  2. start it. 
  3. in my case it was running fine apparently but failed at connecting with SSH "Failed to connect to the CRC VM with SSH -- virtual machine might be unreachable: Temporary error: ssh command"
  4. stop it
  5. start again
  6. if fails with error below

### Actual

```
./out/macos-arm64/crc start --bundle ~/Downloads/crc_microshift_vfkit_4.17.8_amd64_990.crcbundle
/usr/bin/security -I
/usr/bin/security delete-generic-password -s crc-test -a foo
WARN Using crc_microshift_vfkit_4.17.8_amd64_990.crcbundle bundle, but crc_microshift_vfkit_4.17.7_arm64.crcbundle is expected for this release 
INFO Using bundle path /Users/luca/Downloads/crc_microshift_vfkit_4.17.8_amd64_990.crcbundle 
INFO Checking if running macOS version >= 13.x    
sw_vers -productVersion
INFO Checking if running as non-root              
INFO Checking if crc-admin-helper executable is cached 
INFO Checking if running on a supported CPU architecture 
INFO Checking if crc executable symlink exists    
INFO Checking minimum RAM requirements            
INFO Check if Podman binary exists in: /Users/luca/.crc/bin/oc 
INFO Checking if running emulated on Apple silicon 
INFO Checking if vfkit is installed               
INFO Checking if old launchd config for tray and/or daemon exists 
INFO Checking if crc daemon plist file is present and loaded 
bash -c launchctl list | grep com.redhat.crc.daemon | awk '{print $1}'
INFO Checking SSH port availability               
INFO Loading bundle: crc_microshift_vfkit_4.17.8_amd64_990... 
/usr/bin/security find-generic-password -s crc -wa compressed-pull-secret
INFO Creating CRC VM for MicroShift 4.17.8...     
INFO Generating new SSH key pair...               
INFO Starting CRC VM for microshift 4.17.8...     
/Users/luca/Public/Work/github.com/crc/crc/out/macos-arm64/vfkit --cpus 2 --memory 4096 --bootloader efi,variable-store=/Users/luca/.crc/machines/crc/efistore.nvram,create --device virtio-serial,logFilePath=/Users/luca/.crc/machines/crc/vfkit.log --device virtio-fs,sharedDir=/Users/luca,mountTag=dir0 --device virtio-rng --device virtio-blk,path=/Users/luca/.crc/machines/crc/crc.img --device virtio-vsock,port=1024,socketURL=/Users/luca/.crc/tap.sock,listen --timesync vsockPort=1234
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10559d2a0]

goroutine 1 [running]:
github.com/crc-org/crc/v2/pkg/drivers/vfkit.(*Driver).Start(0x14000218a00)
	/Users/luca/Public/Work/github.com/crc/crc/pkg/drivers/vfkit/driver_darwin.go:282 +0x7c0
github.com/crc-org/crc/v2/pkg/crc/machine.startHost({0x106318c48, 0x14000762190}, 0x14000218b40)
	/Users/luca/Public/Work/github.com/crc/crc/pkg/crc/machine/start.go:702 +0x40
github.com/crc-org/crc/v2/pkg/crc/machine.(*client).Start(0x1400072d940, {0x106318c48, 0x14000762190}, {{0x16bd1788d, 0x45}, 0x1000, 0x2, 0x1f, {0x0, 0x0}, ...})
	/Users/luca/Public/Work/github.com/crc/crc/pkg/crc/machine/start.go:384 +0xde0
github.com/crc-org/crc/v2/pkg/crc/machine.(*Synchronized).Start(0x1400072d980, {0x106318c10?, 0x14000519560?}, {{0x16bd1788d, 0x45}, 0x1000, 0x2, 0x1f, {0x0, 0x0}, ...})
	/Users/luca/Public/Work/github.com/crc/crc/pkg/crc/machine/sync.go:93 +0xa8
github.com/crc-org/crc/v2/cmd/crc/cmd.runStart({0x106318c10, 0x14000519560})
	/Users/luca/Public/Work/github.com/crc/crc/cmd/crc/cmd/start.go:117 +0x4b8
github.com/crc-org/crc/v2/cmd/crc/cmd.init.func11(0x107486c20, {0x9?, 0x14000697c18?, 0x0?})
	/Users/luca/Public/Work/github.com/crc/crc/cmd/crc/cmd/start.go:57 +0x58
github.com/crc-org/crc/v2/cmd/crc/cmd.attachMiddleware.executeWithLogging.func1(0x107486c20, {0x14000461be0, 0x0, 0x2})
	/Users/luca/Public/Work/github.com/crc/crc/cmd/crc/cmd/root.go:170 +0xb0
github.com/spf13/cobra.(*Command).execute(0x107486c20, {0x14000461bc0, 0x2, 0x2})
	/Users/luca/Public/Work/github.com/crc/crc/vendor/github.com/spf13/cobra/command.go:985 +0x834
github.com/spf13/cobra.(*Command).ExecuteC(0x107486660)
	/Users/luca/Public/Work/github.com/crc/crc/vendor/github.com/spf13/cobra/command.go:1117 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/luca/Public/Work/github.com/crc/crc/vendor/github.com/spf13/cobra/command.go:1041
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/Users/luca/Public/Work/github.com/crc/crc/vendor/github.com/spf13/cobra/command.go:1034
github.com/crc-org/crc/v2/cmd/crc/cmd.Execute()
	/Users/luca/Public/Work/github.com/crc/crc/cmd/crc/cmd/root.go:106 +0xcc
main.main()
	/Users/luca/Public/Work/github.com/crc/crc/cmd/crc/main.go:8 +0x1c
```

### Logs

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```

Please consider posting the output of `crc start --log-level debug`  on http://gist.github.com/ and post the link in the issue.

**Comment by lstocchi** [comment]
wrong repo
